#pragma once
#include "Headers.h"


enum class ForegroundColor
{
	BLACK = 0,
	BLUE = FOREGROUND_BLUE | FOREGROUND_INTENSITY,
	GREEN = FOREGROUND_GREEN | FOREGROUND_INTENSITY,
	DARKCYAN = FOREGROUND_BLUE | FOREGROUND_GREEN,
	DARKRED = FOREGROUND_RED,
	MAGENTA = FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY,
	WHITE = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY,
	RED = FOREGROUND_RED | FOREGROUND_INTENSITY,
	YELLOW = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY,
	CYAN = FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_INTENSITY,
	GREY = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,
	DARKBLUE = FOREGROUND_BLUE,
	DARKGREEN = FOREGROUND_GREEN,
	DARKYELLOW = FOREGROUND_RED | FOREGROUND_GREEN,
	DARKMAGENTA = FOREGROUND_RED | FOREGROUND_BLUE,
	DARKGREY = FOREGROUND_INTENSITY 
};

enum class BackgroundColor
{
	BLACK = 0,
	WHITE = BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY,
	GREY = BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE,
	GREEN = BACKGROUND_GREEN | BACKGROUND_INTENSITY,
	RED = BACKGROUND_RED | BACKGROUND_INTENSITY,
	DARKRED = BACKGROUND_RED,
	DARKGREEN = BACKGROUND_GREEN,
	DARKBLUE = BACKGROUND_BLUE,
	CYAN = BACKGROUND_BLUE | BACKGROUND_GREEN 
};




